kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sample-backend-dc
  namespace: backend
spec:
#  replicas: 1
#  revisionHistoryLimit: 2 
  template:
    metadata:
      name: sample-backend
      labels:
        app: sample-backend
#        role: backend
#        env: dev
    spec:
      containers:
      - name: sample-backend
        image: asia.gcr.io/gdg-demo-165104/kube-sample-backend
#        resources:
#          limits:
#            memory: "500Mi"
#            cpu: "100m"
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 80
        ports:
        - name: sample-backend
          containerPort: 8080