kind: Service
apiVersion: v1
metadata:
  name: sample-backend-svc
  namespace: backend
spec:
  type: LoadBalancer
#  loadBalancerIP: 104.199.190.226
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: sample-backend
#    role: backend